def createRepo(request):
    
    # Cloud function with http trigger to create a github repo
    """ HTTP Cloud Function"""

    from github import Github
    import requests
    import pygit2
    import shutil
    import os

    def createRepo(githubUser,githubToken,repoName):
        g = Github(githubToken)
        user = g.get_user(githubUser)
        repo = user.create_repo(repoName, description='Repo Auto-Generated by Cloud Function', private=True)
        return repo

    # Initialize github user and github token
    githubUser = "PUT_GITHUB_USER_HERE"
    githubToken = "PUT_GITHUB_TOKEN_HERE"
    # Get new repo name and the name of repo to clone
    repoName = request.args.get('repoName', '')
    repo = createRepo(githubUser,githubToken, repoName)
    # create README.md
    repo.create_file('README.md', 'init commit', '# '+repoName)
    print('Repo '+ repoName +' created with README.md')