def createRepo(request):
    
    # Cloud function with http trigger to create a github repo
    """ HTTP Cloud Function"""

    from github import Github
    import requests
    import pygit2
    import shutil
    import os

    # Initialize github user and github token
    githubUser = "JunchengL"
    githubToken = "PUT_YOUR_TOKEN"
    # Get new repo name and the name of repo to clone
    g = Github(githubToken)
    #print(user)
    repoName = request.args.get('repoName', '')
    repo=g.get_user().create_repo(repoName, description='Repo Auto-Generated by Cloud Function', private=True)
    # create README.md
    repo.create_file('README.md', 'init commit', '# '+repoName)
    print('Repo '+ repoName +' created with README.md')
